import { useEffect, useMemo, useRef, useState } from "react";

const DEFAULT_HTML = `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><style>*{box-sizing:border-box}html,body{margin:0;width:1280px;height:720px;overflow:hidden}body{display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#0f0c29,#302b63,#24243e);font-family:Arial;color:#fff}.card{text-align:center;animation:rise .9s ease both}h1{font-size:74px;margin:0 0 16px;background:linear-gradient(90deg,#a78bfa,#60a5fa,#34d399);-webkit-background-clip:text;color:transparent}p{font-size:24px;opacity:.75}@keyframes rise{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:none}}</style></head><body><div class="card"><h1>HTML → VIDEO</h1><p>صمّم المشهد ثم صدّره MP4 عبر Chromium + FFmpeg</p></div></body></html>`;
const tabs=[['editor','المحرر'],['preview','المعاينة'],['chat','ChatGPT'],['history','التسجيلات']];
const presets=[[1280,720,'16:9'],[1080,1920,'9:16'],[1080,1080,'1:1']];
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
function Bubble({m}){return <div style={{display:'flex',justifyContent:m.role==='user'?'flex-end':'flex-start',marginBottom:9}}><div style={{maxWidth:'88%',padding:'10px 13px',borderRadius:14,background:m.role==='user'?'linear-gradient(135deg,#4f46e5,#7c3aed)':'rgba(255,255,255,.06)',border:m.role==='user'?'none':'1px solid rgba(255,255,255,.1)',whiteSpace:'pre-wrap',lineHeight:1.55,fontSize:13}}>{m.content}</div></div>}
export default function App(){
 const [tab,setTab]=useState('editor'),[html,setHtml]=useState(DEFAULT_HTML),[key,setKey]=useState(0),[input,setInput]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[rendering,setRendering]=useState(false),[status,setStatus]=useState(''),[history,setHistory]=useState([]),[duration,setDuration]=useState(5),[fps,setFps]=useState(30),[width,setWidth]=useState(1280),[height,setHeight]=useState(720),[health,setHealth]=useState({openai:false,renderer:false,model:''});
 const file=useRef(null);const animated=useMemo(()=>/@keyframes|animation\s*:|transition\s*:|requestAnimationFrame/.test(html),[html]);
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>{})},[]);
 async function ask(mode){const text=input.trim();if(!text||busy)return;setInput('');setBusy(true);const user={role:'user',content:text};setMessages(x=>[...x,user]);try{const system=mode==='editor'?`أنت مصمم HTML وThree.js متخصص في إنتاج مشاهد قابلة للرندر بواسطة Chromium وFFmpeg. أعد HTML كاملاً داخل كتلة html. اجعل الأنيميشن يبدأ تلقائياً. عند استخدام Canvas/WebGL أضف window.HTML_VIDEO_READY=true بعد اكتمال التهيئة عند الحاجة. الصفحة الحالية:\n${html}`:`أنت مساعد تقني داخل HTML-to-VIDEO. حلل الصفحة الحالية واقترح تحسينات للرندر. إذا طلب المستخدم كوداً، أعد HTML كاملاً داخل كتلة html.\n${html}`;const d=await api('/api/openai',{messages:[...messages,user],system});const textOut=d.text||'';setMessages(x=>[...x,{role:'assistant',content:textOut}]);const m=textOut.match(/```html\n?([\s\S]*?)```/i)||textOut.match(/```\n?([\s\S]*?)```/i);const next=m?m[1].trim():(textOut.includes('<html')?textOut.trim():null);if(next){setHtml(next);setKey(x=>x+1);setTab('preview')}}catch(e){setMessages(x=>[...x,{role:'assistant',content:`❌ ${e.message}`}])}finally{setBusy(false)}}
 function importHtml(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{setHtml(String(r.result||''));setKey(x=>x+1)};r.readAsText(f);e.target.value=''}
 async function render(){if(rendering)return;setRendering(true);setStatus('جاري تشغيل Chromium…');try{const fd=new FormData();fd.append('html',new File([html],'scene.html',{type:'text/html'}));fd.append('duration',duration);fd.append('width',width);fd.append('height',height);fd.append('fps',fps);const r=await fetch('/render',{method:'POST',body:fd});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||`HTTP ${r.status}`)}setStatus('جاري تنزيل MP4…');const blob=await r.blob();const url=URL.createObjectURL(blob);setHistory(x=>[{id:Date.now(),url,blob,html,duration,fps,width,height,size:(blob.size/1048576).toFixed(2),time:new Date().toLocaleTimeString('ar')},...x]);setStatus('✓ تم إنشاء الفيديو');setTab('history')}catch(e){setStatus(`❌ ${e.message}`)}finally{setRendering(false)}}
 function download(x){const a=document.createElement('a');a.href=x.url;a.download=`html-video-${x.id}.mp4`;a.click()}
 const css={bg:'#0b0b12',panel:'rgba(255,255,255,.045)',border:'1px solid rgba(255,255,255,.09)',muted:'#72809a',text:'#e6eaf2',accent:'#6366f1'};const btn=(on=false)=>({border:on?'none':css.border,background:on?css.accent:css.panel,color:on?'#fff':css.text,borderRadius:8,padding:'8px 11px',cursor:'pointer',fontSize:12});
 return <div dir="rtl" style={{minHeight:'100vh',background:css.bg,color:css.text,fontFamily:'Inter,Arial',display:'flex',flexDirection:'column'}}><style>{`*{box-sizing:border-box}body{margin:0}textarea,input,select,button{font:inherit}button:disabled{opacity:.5;cursor:not-allowed}`}</style>
 <header style={{height:58,display:'flex',alignItems:'center',gap:12,padding:'0 16px',borderBottom:css.border}}><b>🎬 HTML<span style={{color:'#a5b4fc'}}>→</span>VIDEO</b><nav style={{display:'flex',gap:4,flex:1}}>{tabs.map(([k,l])=><button key={k} style={btn(tab===k)} onClick={()=>setTab(k)}>{l}{k==='history'&&history.length?` (${history.length})`:''}</button>)}</nav><span style={{fontSize:11,color:health.openai?'#34d399':'#f87171'}}>● OpenAI</span><span style={{fontSize:11,color:health.renderer?'#a78bfa':'#f87171'}}>● Engine</span><button disabled={rendering} onClick={render} style={{...btn(true),background:rendering?'#374151':'#ef4444',fontWeight:800}}>{rendering?'⏳ رندر…':'🎬 إنشاء MP4'}</button></header>
 <section style={{display:'flex',gap:7,padding:8,borderBottom:css.border,alignItems:'center',flexWrap:'wrap'}}><button style={btn()} onClick={()=>file.current?.click()}>📂 استيراد HTML</button><input ref={file} hidden type="file" accept=".html,.htm,text/html" onChange={importHtml}/><button style={btn()} onClick={()=>{setHtml(DEFAULT_HTML);setKey(x=>x+1)}}>↺ افتراضي</button>{presets.map(([w,h,l])=><button key={l} style={btn(width===w&&height===h)} onClick={()=>{setWidth(w);setHeight(h)}}>{l}</button>)}<label style={{fontSize:11,color:css.muted}}>مدة <select value={duration} onChange={e=>setDuration(+e.target.value)}><option>3</option><option>5</option><option>10</option><option>15</option><option>30</option></select></label><label style={{fontSize:11,color:css.muted}}>FPS <select value={fps} onChange={e=>setFps(+e.target.value)}><option>15</option><option>24</option><option>30</option></select></label><span style={{marginInlineStart:'auto',fontSize:11,color:css.muted}}>{width}×{height}{animated?' · ✨ animation':''}{health.model?` · ${health.model}`:''}</span></section>
 {tab==='editor'&&<main style={{flex:1,minHeight:0,display:'grid',gridTemplateColumns:'1fr 380px'}}><textarea value={html} onChange={e=>setHtml(e.target.value)} spellCheck={false} style={{width:'100%',height:'100%',minHeight:0,resize:'none',background:'#08080e',color:'#b7c3ff',border:0,padding:18,fontFamily:'ui-monospace,monospace',fontSize:13}}/><aside style={{borderInlineStart:css.border,padding:14,overflowY:'auto'}}><h3>ChatGPT — مساعد الكود</h3><div style={{color:css.muted,fontSize:12,marginBottom:10}}>اطلب إنشاء أو تعديل المشهد.</div>{['اصنع أنيميشن نص متحرك','أضف خلفية جسيمات','حوّل المشهد إلى فيديو عمودي','أضف مؤثرات Three.js'].map(s=><button key={s} style={{...btn(),width:'100%',marginBottom:6,textAlign:'right'}} onClick={()=>setInput(s)}>{s}</button>)}<ChatInput input={input} setInput={setInput} busy={busy} send={()=>ask('editor')}/></aside></main>}
 {tab==='preview'&&<main style={{flex:1,display:'flex',flexDirection:'column',alignItems:'center',gap:12,padding:18,overflow:'auto'}}><div style={{width:'min(100%,960px)',aspectRatio:`${width}/${height}`,background:'#000',border:css.border,borderRadius:10,overflow:'hidden'}}><iframe key={key} srcDoc={html} title="preview" sandbox="allow-scripts allow-same-origin" style={{width:'100%',height:'100%',border:0}}/></div><div style={{display:'flex',gap:8}}><button style={btn()} onClick={()=>setKey(x=>x+1)}>🔄 إعادة التشغيل</button><button style={{...btn(true),background:'#ef4444'}} onClick={render}>🎬 إنشاء MP4</button></div>{status&&<div style={{fontSize:12,color:status.startsWith('❌')?'#f87171':'#c7d2fe'}}>{status}</div>}</main>}
 {tab==='chat'&&<main style={{flex:1,minHeight:0,display:'grid',gridTemplateColumns:'1fr 420px'}}><div style={{display:'flex',alignItems:'center',justifyContent:'center',padding:18}}><div style={{width:'100%',maxWidth:800,aspectRatio:`${width}/${height}`,background:'#000',border:css.border,borderRadius:10,overflow:'hidden'}}><iframe key={key} srcDoc={html} title="interactive" sandbox="allow-scripts allow-same-origin" style={{width:'100%',height:'100%',border:0}}/></div></div><aside style={{borderInlineStart:css.border,padding:14,display:'flex',flexDirection:'column',minHeight:0}}><h3>ChatGPT — الجلسة التفاعلية</h3><div style={{flex:1,overflowY:'auto'}}>{messages.map((m,i)=><Bubble key={i} m={m}/>)}{busy&&<div style={{color:css.muted}}>ChatGPT يفكر…</div>}</div><ChatInput input={input} setInput={setInput} busy={busy} send={()=>ask('chat')}/></aside></main>}
 {tab==='history'&&<main style={{flex:1,padding:18,overflow:'auto'}}>{!history.length?<div style={{textAlign:'center',color:css.muted,paddingTop:70}}>لا توجد تسجيلات بعد</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(320px,1fr))',gap:14}}>{history.map(x=><article key={x.id} style={{background:css.panel,border:css.border,borderRadius:10,overflow:'hidden'}}><video src={x.url} controls style={{width:'100%',aspectRatio:`${x.width}/${x.height}`,background:'#000'}}/><div style={{padding:12,fontSize:12}}>{x.width}×{x.height} · {x.duration}ث · {x.fps}fps · {x.size}MB<div style={{display:'flex',gap:7,marginTop:8}}><button style={{...btn(true),flex:1}} onClick={()=>download(x)}>⬇️ تنزيل</button><button style={{...btn(),flex:1}} onClick={()=>{setHtml(x.html);setTab('editor');setKey(k=>k+1)}}>✏️ تعديل</button></div></div></article>)}</div>}</main>}
 </div>}
function ChatInput({input,setInput,busy,send}){return <div style={{display:'flex',gap:7,marginTop:10}}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} rows={3} placeholder="اطلب تعديلاً أو اسأل عن الكود…" style={{flex:1,resize:'none',background:'rgba(255,255,255,.05)',border:'1px solid rgba(255,255,255,.09)',color:'#fff',borderRadius:8,padding:9}}/><button disabled={busy||!input.trim()} onClick={send} style={{background:'#6366f1',color:'#fff',border:0,borderRadius:8,padding:'0 14px'}}>↑</button></div>}
